---
# Deploy Galaxy config files (galaxy.yml, tool configs, local tools) and lint TPV rules.
# Runs galaxyproject.galaxy static_setup + usegalaxy_eu.tpv_auto_lint. No code update, no restart.

- name: Galaxy Configuration Update
  hosts: galaxyservers
  become_user: galaxy_master
  vars:
  pre_tasks:
    - name: Load TPV python blobs
      set_fact:
        tpv_debug: "{{ inventory_dir }}/../files/galaxy/config/tpv/tpv_debug.py"
        # tpv_debug: "{{ lookup('file', 'files/galaxy/config/tpv/tpv_debug.py') }}"
    - name: Print
      debug:
        msg: "galaxy_server_dir: {{ galaxy_server_dir }}"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyproject.galaxy
      galaxy_separate_privileges: no
      galaxy_manage_clone: no
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_subdomain_static: no
      # galaxy_manage_themes: "{{ __galaxy_manage_themes | default(true) }}"
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      galaxy_build_client: no
      galaxy_manage_systemd: no
      galaxy_manage_gravity: no

    # Adds a TPV (Total Perspective Vortex) lint script that automatically lints all TPV YAML files
    # some custom changes to allow a different user than root to install scripts and copy tpv related files

    - role: usegalaxy_eu.tpv_auto_lint
      # become: true
      # become_user: "{{ galaxy_user_name }}"
  handlers:
  #TODO: Include a handler to reload toolbox