---
- name: Manage authorized_keys entry
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ssh_authorized_keys }}"
