{
 "title": "Cluster Status",
 "description": "Current Galaxy Belgium compute cluster load: use this to get an idea of how busy the cluster is and how long your jobs might take to start.",
 "tags": [
  "public",
  "status"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs in Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"count\") FROM \"jobs-queued\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Jobs Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"claimed_busy_slots\") FROM \"htcondor_cluster_usage\" WHERE \"classad\" = 'machine' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Available CPU Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"unclaimed_cpus\") FROM \"htcondor_cluster_usage\" WHERE \"classad\" = 'machine' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total CPU Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total_detected_cpus\") FROM \"htcondor_cluster_usage\" WHERE \"classad\" = 'machine' AND $timeFilter"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Job Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT last(\"count\") AS \"queued\" FROM \"jobs-queued\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT last(\"claimed_cpus\") AS \"in use\", last(\"unclaimed_cpus\") AS \"available\", last(\"total_detected_cpus\") AS \"total\" FROM \"htcondor_cluster_usage\" WHERE \"classad\" = 'machine' AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  { "title": "Queue by Destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Jobs Queued per Destination",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT last(\"count\") FROM \"queue_by_destination\" WHERE \"state\" = 'queued' AND \"destination_id\" != 'none' AND $timeFilter GROUP BY time($__interval), \"destination_id\" fill(0)"
    }
   ]
  }
 ]
}