{
 "title": "day-to-day",
 "tags": [ "Production" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "jwd_max",
    "query": "SELECT last(\"total\")  / (1024*1024*1024*1024) FROM \"disk\" WHERE (\"host\" = 'usegalaxy.be' AND \"device\" =~ /^.*jwd*/) AND $timeFilter GROUP BY \"device\""
   },
   {
    "name": "Schedd",
    "query": "SHOW TAG VALUES FROM \"cluster.queue\" WITH KEY = \"schedd\""
   }
  ]
 },
 "panels": [
  { "title": "Galaxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job queue - current status",
   "type": "stat",
   "description": "Gives an overview of the current status of the Galaxy job queue.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "new" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "queued" }
     ]
    },
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": " Queued jobs (with or without condor ids)",
   "type": "timeseries",
   "description": "Shows the distribution of jobs in the queued state, categorized as processed and unprocessed depending on whether they have received an external  (HTCondor) ID or not.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Jobs per destination - Overview",
   "type": "table",
   "description": "Gives an overview of the number of running and queued jobs per destination.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "destination_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "queue_by_destination",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " Queued jobs (with or without condor ids) - current status",
   "type": "stat",
   "description": "Shows the distribution of jobs in the queued state, categorized as processed and unprocessed depending on whether they have received an external  (HTCondor) ID or not.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Job queue",
   "type": "timeseries",
   "description": "Time-series showing the status of Galaxy jobs.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'queued') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" }
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'new') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy JWDs - Overview",
   "type": "barchart",
   "description": "Shows the storage overview of Galaxy JWD's. ",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\")  / (1024*1024*1024*1024) AS \"total\" FROM \"disk\" WHERE (\"host\" =~  /^$Schedd$/ AND \"device\" =~ /^.*jwd*|^.*cache*|^.*misc*/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    },
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\")  / (1024*1024*1024*1024) AS \"used\" FROM \"disk\" WHERE (\"host\" =~  /^$Schedd$/ AND \"device\" =~ /^.*jwd*|^.*cache*|^.*misc*/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    },
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"free\")  / (1024*1024*1024*1024) AS \"free\" FROM \"disk\" WHERE (\"host\" =~  /^$Schedd$/ AND \"device\" =~ /^.*jwd*|^.*cache*|^.*misc*/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "description": "Shows the number of currently active users logged in on the https://usegalaxy.eu (recorded every 10 minutes).",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "active_users",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = \"^$Schedd$/\") AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Jobs per handler - Overview",
   "type": "table",
   "description": "Shows the number of jobs handled by each job handler. Each job handler is run as a systemd service.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "handler" ], "type": "tag" }
     ],
     "measurement": "galaxy_jobs_per_handler_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy handlers last log entry",
   "type": "stat",
   "description": "Shows the number of seconds since the last log entry. If the entry was a bit old then the respective handler might have some issues. So, this helps to investigate the corresponding handler. Each handler is run as a systemd service.",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "journalctl.lastlog",
     "query": "SELECT last(\"seconds\") FROM \"journalctl.lastlog\" WHERE (\"host\" =~ /usegalaxy.be/ AND \"service\" =~ /galaxy-handler@[0-1]/) AND $timeFilter GROUP BY time($interval), \"service\"",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Schedd$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/galaxy-handler@[0-5]/" }
     ]
    }
   ]
  },
  {
   "title": "Active users over time",
   "type": "timeseries",
   "description": "Shows the number of currently active users who are logged in on the usegalaxy.eu website (recorded every 10 minutes)",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "active_users",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'usegalaxy.be')",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "(WIP) Status of all critical services ",
   "type": "timeseries",
   "description": "This panel shows the list of services (e.g., tusd, celery, Galaxy, rabbitmq, etc.) and their statuses.",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 28 }
  },
  {
   "title": "Galaxy user file source utilisation",
   "type": "barchart",
   "description": "Shows how many users are using which template.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "template_id::tag" ], "type": "tag" }
     ],
     "measurement": "user_file_source_utilisation",
     "query": "SELECT last(\"user_count\") as \"Count\" FROM \"user_file_source_utilisation\" GROUP BY \"template_id\"::tag",
     "select": [
      [
       { "params": [ "user_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy user object source utilisation",
   "type": "barchart",
   "description": "Shows how many users are using which template.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "template_id::tag" ], "type": "tag" }
     ],
     "measurement": "user_object_store_utilisation",
     "query": "SELECT LAST(\"user_count\") as \"Count\" FROM \"user_object_store_utilisation\" GROUP BY \"template_id\"::tag",
     "select": [
      [
       { "params": [ "user_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Services status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "SystemD units status",
   "type": "table",
   "description": "Shows the status of the systemd units status. For details refer to the [Telegraf plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/systemd_units/README.md)",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "SELECT last(*) FROM \"systemd_units\""
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"systemd_units\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HTCondor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "HTCondor job queue - overview",
   "type": "timeseries",
   "description": "Gives an overview of the current status of the jobs in the HTCondor queue.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "cluster.queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor job queue - overview",
   "type": "stat",
   "description": "Gives an overview of the current status of the jobs in the HTCondor queue.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "schedd" ], "type": "tag" }
     ],
     "measurement": "cluster.queue",
     "query": "SELECT mean(\"count\") FROM \"cluster.queue\" WHERE (\"host\" = 'usegalaxy.be') AND $timeFilter GROUP BY time($__interval), \"state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy utilization of HTCondor cluster - Overview",
   "type": "gauge",
   "description": "Shows the resource utilization of the entire HTCondor  cluster utilization by Galaxy",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_detected_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\") /(1024*1024) AS \"Total mem (TiB)\", last(\"claimed_memory\")  /(1024*1024) AS \"Claimed mem (TiB)\", last(\"unclaimed_memory\") /(1024*1024) AS \"Unclaimed mem (TiB)\", last(\"total_gpu_slots\") AS \"Total GPU hosts\", last(\"claimed_gpus\") AS \"Claimed GPU hosts\", last(\"unclaimed_gpus\") AS \"Unclaimed GPU hosts\", last(\"total_slots\") AS \"Total slots\", last(\"claimed_busy_slots\") AS \"Claimed busy slots\", last(\"unclaimed_idle_slots\") AS \"Unclaimed idle slots\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'machine\\'') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_detected_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "total_gpu_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_busy_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed busy slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_idle_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed idle slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'machine'" }
     ]
    }
   ]
  },
  {
   "title": "Condor queued jobs and their status",
   "type": "table",
   "description": "This panel shows the real-time information of the condor queue. It also shows the compute resources requested by the job, when it was submitted to the queue, and when it started. \n\nNote:\n1. *undefined => The respective data was unavailable because the job had not yet started or was on hold or idle.\n2. Sometimes, request memory could be more than defined for the tool in the TPV tools.yml or the TPV shared database because we have a dedicated script that resubmits the job if it needs more memory up to a certain number of times.",
   "gridPos": { "h": 15, "w": 21, "x": 0, "y": 60 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "clusterid" ], "type": "tag" }
     ],
     "measurement": "condor_queued_jobs_status",
     "select": [
      [
       { "params": [ "jobstatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Status" ], "type": "alias" }
      ],
      [
       { "params": [ "cmd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cmd" ], "type": "alias" }
      ],
      [
       { "params": [ "jobdescription" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Description" ], "type": "alias" }
      ],
      [
       { "params": [ "remotehost" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Remote Host" ], "type": "alias" }
      ],
      [
       { "params": [ "requestcpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Request CPUs (cores)" ], "type": "alias" }
      ],
      [
       { "params": [ "requestmemory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" },
       { "params": [ "Request Memory (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "qdate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Queued Date" ], "type": "alias" }
      ],
      [
       { "params": [ "jobstartdate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Start Date" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster slots per group",
   "type": "stat",
   "description": "Shows the dynamic slots distribution across different groups (only important groups are shown). This gives an idea of what slots are available and free.",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_group - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\", last(\"unclaimed_slots\") AS \"Unclaimed slots\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'') AND $timeFilter GROUP BY time($interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Compute",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute.",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\", last(\"unclaimed_slots\") AS \"Unclaimed slots\", last(\"total_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\")  /(1024 * 1024) AS \"Total mem (TiB)\", last(\"claimed_memory\")  /(1024*1024) AS \"Claimed mem (TiB)\", last(\"unclaimed_memory\")  /(1024*1024) AS \"Unclaimed mem (TiB)\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024 * 1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Compute GPU",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute GPU",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\", last(\"unclaimed_slots\") AS \"Unclaimed slots\", last(\"total_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\") /1024 AS \"Total mem (GiB)\", last(\"claimed_memory\")  /1024 AS \"Claimed mem (GiB)\", last(\"unclaimed_memory\") /1024 AS \"Unclaimed mem (GiB)\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute_gpu') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute_gpu" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Interactive",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Interactive",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\", last(\"unclaimed_slots\") AS \"Unclaimed slots\", last(\"total_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\") /1024 AS \"Total mem (GiB)\", last(\"claimed_memory\")  /1024 AS \"Claimed mem (GiB)\", last(\"unclaimed_memory\") /1024 AS \"Unclaimed mem (GiB)\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'interactive') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "interactive" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Upload",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Upload",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\", last(\"unclaimed_slots\") AS \"Unclaimed slots\", last(\"total_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\") /1024 AS \"Total mem (GiB)\", last(\"claimed_memory\")  /1024 AS \"Claimed mem (GiB)\", last(\"unclaimed_memory\") /1024 AS \"Unclaimed mem (GiB)\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'upload') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "upload" }
     ]
    }
   ]
  },
  {
   "title": "About the Upload group ",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 105 },
   "options": {
    "content": "Compute group \"Upload\" is dedicated exclusively to integrating uploaded files into Galaxy as datasets.\nAt the moment, there are [no machines in the \"upload\" group](https://github.com/usegalaxy-eu/vgcn-infrastructure/commit/052e137a9b06238ea74167e6b38f673c0f11f721).\n\nUpload jobs (`__DATA_FETCH__` tool identifier) are sent by [TPV](https://github.com/galaxyproject/total-perspective-vortex) to the\n[`condor_upload` destination](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/c6b1447bde8cd4fefc73a9f40c6382eadc450ff3/files/galaxy/tpv/destinations.yml.j2#L425-L436)\nfollowing [this rule](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/c6b1447bde8cd4fefc73a9f40c6382eadc450ff3/files/galaxy/tpv/tools.yml#L14-L38). Note\nthat the destination settings imply upload jobs prefer machines from the \"upload\" group, but can also run in other groups.\n"
   }
  },
  {
   "title": "PXE Disk Setup",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 111 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "pxe.disk_mode",
     "select": [
      [
       { "params": [ "disksetup_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Disk found?" ], "type": "alias" }
      ],
      [
       { "params": [ "openslx_label" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Disk labelled?" ], "type": "alias" }
      ],
      [
       { "params": [ "scratch_mounted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Scratch mounted?" ], "type": "alias" }
      ],
      [
       { "params": [ "nfs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFS?" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "sn09 server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Current Disk Usage",
   "type": "table",
   "description": "Shows the sn06's (Galaxy master node) current disk usage",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 120 },
   "targets": [
    {
     "alias": "[[tag_fstype]] @ [[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"fstype\", \"path\" fill(none)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Shows the sn06's (Galaxy master node) CPU utilization",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows the sn06's (Galaxy master node) memory usage",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cached" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Server load",
   "type": "timeseries",
   "description": "Shows the sn06's (Galaxy master node) 1, 5, and 15 minute load average",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "timeseries",
   "description": "Shows the sn06's (Galaxy master node) current disk IO",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  }
 ]
}