{
 "title": "Galaxy",
 "tags": [ "galaxy" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Galaxy host",
    "query": "SHOW TAG VALUES FROM \"cluster.queue\" WITH KEY = \"schedd\""
   }
  ]
 },
 "panels": [
  {
   "title": "The UseGalaxy.BE Queue",
   "type": "text",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "## About\n\nThese graphs show you the current status of our clusters and which tools are being run on [UseGalaxy.be](https://usegalaxy.be). Our primary cluster is a Condor cluster running in the [Flemish Supercomputer Center tier-1 Cloud](https://docs.vscentrum.be/cloud/index.html)."
   }
  },
  {
   "title": "Active Users (10 minutes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "active_users",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'usegalaxy.be') AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Galaxy Unscheduled Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Queued Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Condor Job States",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.queue",
     "query": "SELECT mean(\"count\") FROM \"cluster.queue\" WHERE (\"host\" = 'usegalaxy.be') AND $timeFilter GROUP BY time($__interval), \"state\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" }
     ]
    }
   ]
  },
  { "title": "UseGalaxy.eu Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Galaxy Running Tools",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Data Upload / Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "general compute`",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "upload-gb-in-past-hour",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "Job Destinations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Pulsar",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "destination_id::tag", "operator": "=~", "value": "/pulsar/" }
     ]
    },
    {
     "alias": "Not Pulsar",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "usegalaxy.be" },
      { "condition": "AND", "key": "job_runner_name", "operator": "!~", "value": "/pulsar/" },
      { "condition": "AND", "key": "job_runner_name::tag", "operator": "=", "value": "condor" }
     ]
    }
   ]
  },
  { "title": "Galaxy / Route Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Galaxy Route Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "90th percentile (api)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^api.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^(api|web|library)/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "90th percentile (web)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^web/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Host / System Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "usegalaxy.be" }
     ]
    }
   ]
  },
  {
   "title": "User based repository utilisation (BYOD)",
   "type": "barchart",
   "description": "Shows how many users are using which template.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "template_id::tag" ], "type": "tag" }
     ],
     "measurement": "user_file_source_utilisation",
     "query": "SELECT last(\"user_count\") as \"Count\" FROM \"user_file_source_utilisation\" GROUP BY \"template_id\"::tag",
     "select": [
      [
       { "params": [ "user_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User based Galaxy storage usage (BYOS)",
   "type": "barchart",
   "description": "Shows how many users are using which template.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "template_id::tag" ], "type": "tag" }
     ],
     "measurement": "user_object_store_utilisation",
     "query": "SELECT LAST(\"user_count\") as \"Count\" FROM \"user_object_store_utilisation\" GROUP BY \"template_id\"::tag",
     "select": [
      [
       { "params": [ "user_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy utilization of HTCondor cluster - Overview",
   "type": "gauge",
   "description": "Shows the resource utilization of the entire HTCondor  cluster utilization by Galaxy",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_detected_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\", last(\"unclaimed_cpus\") AS \"Unclaimed CPU cores\", last(\"total_memory\") /(1024*1024) AS \"Total mem (TiB)\", last(\"claimed_memory\")  /(1024*1024) AS \"Claimed mem (TiB)\", last(\"unclaimed_memory\") /(1024*1024) AS \"Unclaimed mem (TiB)\", last(\"total_gpu_slots\") AS \"Total GPU hosts\", last(\"claimed_gpus\") AS \"Claimed GPU hosts\", last(\"unclaimed_gpus\") AS \"Unclaimed GPU hosts\", last(\"total_slots\") AS \"Total slots\", last(\"claimed_busy_slots\") AS \"Claimed busy slots\", last(\"unclaimed_idle_slots\") AS \"Unclaimed idle slots\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'machine\\'') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_detected_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "total_gpu_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_busy_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed busy slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_idle_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed idle slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'machine'" }
     ]
    }
   ]
  }
 ]
}