# pdg.create-paths

# rw_dirs = galaxy_dirs

# galaxy_local_rw_dirs:
#   # TODO: figure out if it's fine to have galaxy_mutable_data_dir locally or not
#   - "{{ galaxy_mutable_data_dir }}"
#   - "{{ galaxy_mutable_config_dir }}"
#   - "{{ galaxy_cache_dir }}"
#   - "{{ galaxy_log_dir }}"
#   - "{{ galaxy_tool_data_path }}"
#     # TODO: figure out if it's fine to have this locally or not
#   - "{{ galaxy_data_manager_data_path }}"
#   # - "{{ galaxy_shed_tool_data_path }}"
#   # - "{{ galaxy_shed_database_path }}"
#   - "{{ galaxy_tus_upload_store }}"

# galaxy_shared_rw_dirs:
#   - "{{ galaxy_shed_tools_dir }}"
#   - "{{ galaxy_tool_dependency_dir }}"
#   - "{{ galaxy_file_path }}"
#   - "{{ galaxy_new_file_path }}"
#   - "{{ galaxy_job_working_directory }}"
#   - "{{ galaxy_tmp_dir }}"
#   - "{{ galaxy_library_dir }}"


# # ro_dirs = galaxy_privsep_dirs

# galaxy_local_ro_dirs:
#   - "{{ galaxy_config_dir }}"
#   - "{{ tpv_config_dir }}"

# galaxy_shared_ro_dirs:
#   - "{{ galaxy_venv_dir }}"
#   - "{{ galaxy_server_dir }}"
#   - "{{ galaxy_local_tools_dir }}"