{
 "title": "Galaxy Condor Cluster",
 "tags": [
  "galaxy",
  "cloud"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Cluster Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "CPU [[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM [[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Total Cores Allocation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Memory Allocation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VGCN Instances in bwCloud",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_cloud]] v[[tag_vgcn_build]] ([[tag_distribution]] [[tag_distribution_version]])",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "vgcn_build" ], "type": "tag" },
      { "params": [ "distribution" ], "type": "tag" },
      { "params": [ "distribution_version" ], "type": "tag" },
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "exec_alive",
     "select": [
      [
       { "params": [ "alive" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 360" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vgcn_build", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "cloud", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VGCN CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vgcn_build" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"vgcn_build\" =~ /.+/ AND \"host\" != 'localhost.localdomain') AND $timeFilter GROUP BY time(1m), \"vgcn_build\", \"cluster\", \"host\" fill(previous)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "vgcn_build", "operator": "=~", "value": "/.+/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "localhost.localdomain" },
      { "condition": "AND", "key": "cloud", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VGCN Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "vgcn_build", "operator": "=~", "value": "/.+/" },
      { "condition": "AND", "key": "cloud", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "localhost.localdomain" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cloud", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "localhost.localdomain" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]:[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "cloud", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "localhost.localdomain" }
     ]
    }
   ]
  },
  {
   "title": "Condor Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine", "operator": "=", "value": "condor" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vgcn_build" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vgcn_build", "operator": "=~", "value": "/.+/" },
      { "condition": "AND", "key": "cloud", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "localhost.localdomain" },
      {
       "condition": "AND",
       "key": "host",
       "operator": "!=",
       "value": "manager.vgcn.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  }
 ]
}