{
 "title": "Galaxy Main",
 "tags": [ "galaxy" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "Galaxy Host", "query": "localhost" }
  ]
 },
 "panels": [
  { "title": "Galaxy services status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "content": "\n# UseGalaxy.be System status\n\n\n\n\n"
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Queued Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Unscheduled Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" },
      { "condition": "AND", "key": "handler", "operator": "!=", "value": "handler_0" },
      { "condition": "AND", "key": "handler", "operator": "!=", "value": "handler_1" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocations Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "workflow-invocation-status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "handler", "operator": "!=", "value": "_default_" }
     ]
    }
   ]
  },
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Condor Job States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine", "operator": "=", "value": "condor" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "CPU [[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "query": "SELECT mean(\"memory\") FROM \"cluster.alloc\" WHERE time >= now() - 12h GROUP BY time(20s), \"cluster\", \"group\" fill(none);",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM [[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "query": "SELECT mean(\"cores\") FROM \"cluster.alloc\" WHERE time >= now() - 12h GROUP BY time(20s), \"cluster\", \"group\" fill(none);\n",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "UseGalaxy.eu Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Galaxy Running Tools",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Data Upload / Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "general compute`",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "upload-gb-in-past-hour",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Destinations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pulsar",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "job_runner_name", "operator": "=~", "value": "/pulsar/" }
     ]
    },
    {
     "alias": "Not Pulsar",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "job_runner_name", "operator": "!~", "value": "/pulsar/" }
     ]
    }
   ]
  },
  { "title": "Galaxy / Route Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Galaxy Route Timings",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "90th percentile (api)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^api.*/" }
     ]
    },
    {
     "alias": "[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^(api|web|library)/" }
     ]
    },
    {
     "alias": "90th percentile (web)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^web/" }
     ]
    }
   ]
  },
  { "title": "uWSGI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requests / time unit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Socket queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.general",
     "select": [
      [
       { "params": [ "listen_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "listen_queue" ], "type": "alias" }
      ],
      [
       { "params": [ "listen_queue_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "listen_queue_errors" ], "type": "alias" }
      ],
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "signal_queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "exceptions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Busy(1)/Idle(0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "uWSGI Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.sockets",
     "select": [
      [
       { "params": [ "can_offload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "can_offload" ], "type": "alias" }
      ],
      [
       { "params": [ "max_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max_queue" ], "type": "alias" }
      ],
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "shared" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "shared" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Harakiri count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "uWSGI locks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_group]] [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.locks",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Average response time (moving avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "avg_rt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}