#cloud-config

write_files:
-   content: |
         CONDOR_HOST = <vgcn-cm-ip> #<ip address where you can reach VGCN Central Manager>
         ALLOW_WRITE = *
         ALLOW_READ = *
         ALLOW_NEGOTIATOR = *
         ALLOW_OWNER = *
         ALLOW_CLIENT = *
         DAEMON_LIST = MASTER, SCHEDD
         FILESYSTEM_DOMAIN = vgcn
         UID_DOMAIN = vgcn
         TRUST_UID_DOMAIN = True
         SOFT_UID_DOMAIN = True
         # http://research.cs.wisc.edu/htcondor/manual/v8.6/3_5Configuration_Macros.html#sec:Collector-Config-File-Entries
         # Keep classads for only 5 minutes which should mean dead cloud nodes are expired much faster.
         CLASSAD_LIFETIME = 300
         # Try and consider new negotations a little bit sooner?
         NEGOTIATOR_INTERVAL = 30
    owner: centos:centos
    path: /etc/condor/condor_config.local
    permissions: '0644'
 



   
users:
      - name: galaxy_master
        sudo: ALL=(ALL) NOPASSWD:ALL
        uid: 1001
        ssh-authorized-keys:
           - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3jw1QLvAejUupFvqfL6Vy8hk7mEYYqxwWRB1DGvVEdFmjfAZkCHNJa6vnChyufnseEGWfbluv7m884oP8ANQLScXMXv+QL0nnQBQ1hTbNjOut4Ky2/fSiPM1bHVAyZsnpSqjbF3SXblqa8Ghr12K6FCXXZr7UKF0QMoo3D4LSynTCKkGOoeOqQNViWEu0iCaCgGbYh6kZMA4y7D1x6K8HC2c1pVhPzAmPYmCrfMIj8t8k6rmoVkXM3wTtYoWPlMwYtdDHTvw3rx1psEWfsubQfPVIZmoPfzO+QjBlikUKLjUj0kr4zCRgIs3b6QpMqa3qb9Sm/hb3X6b/oQrP6dUL igegu@blanca 
           - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7LmtyEf2d4T+GM8taeuWqt7wdLyjccUhL6fpweit7ZltlD8zxC6OL5LBnjGrMT1j7FQc5/2PCAUChHoVrnM/yPhlkNFqMdPqSlq778kb+SDZqsf755zegc4yzZGfEu9EzK++0WFo8Q3Mdp5vtU/ETXx704OfbO4J79t/+52KquMKjCOBHTX47hVTERc4cYui0qfhG6flo2GgYWyH7YpYgeSBg4zIoKuaaJlgmbfN16AOwSO6D4qmaBHEg4p++M7pfYb0bS5xy3E+F4ak48QtY2fkrqE7vwfSXG+aCRa/dLu5hhI5daJk25YSPRLyGqMALp1KL9/YthhGY5RmRq0AL ieguinoa@borat



