mounts:
  - - '<nfs-ip>:/volumes/_nogroup/6dd884fc-cf20-46f3-bf17-b249ef5ee0a9'
    - '/srv/galaxy/src'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
  - - '<nfs-ip>:/volumes/_nogroup/821963e3-6881-41f2-b84c-7e07ffd066d3'
    - '/srv/galaxy/database'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
  - - '<nfs-ip>:/volumes/_nogroup/41df0e0d-2d90-470c-8a03-23f1b8e0ea57'
    - '/srv/galaxy/all_tmp'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
  - - '<nfs-ip>:/volumes/_nogroup/d36e6731-b883-44b9-8199-d228dfb99c60'
    - '/srv/galaxy/dependencies'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
  - - '<nfs-ip>:/volumes/_nogroup/6c800554-5c9b-4a31-a526-279a610c631d'
    - '/galaxy_base/scratch_prod/dm-data'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'

