mounts:
  - - '<nfs-ip>:/volumes/_nogroup/6dd884fc-cf20-46f3-bf17-b249ef5ee0a9'
    - '/galaxy_base/src_test'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
  - - '<nfs-ip>:/volumes/_nogroup/01a14a82-3dcf-42ee-b22e-0da1a9d6392e'
    - '/galaxy_base/scratch_test'
    - 'nfs'
    - 'defaults'
    - '0'
    - '0'
