# pulsar_server_dir: /opt/pulsar
data_path: "{{galaxy_user_home}}"

copy_metrics_plugins: false
# metrics_plugins_to_copy:
#   - {'src': 'staging_time.py', 'dest': '/opt/pulsar/venv/lib/python2.7/site-packages/galaxy/jobs/metrics/instrumenters/staging_time.py'}

#
# Update hosts script parameters
# the values here depend on what you have set up in your terraform configuration
# see: https://github.com/usegalaxy-eu/pulsar-infrastructure/blob/master/tf/vars.tf
#
name_prefix: "vgcn"
name_suffix: "usegalaxy.be"
private_network_prefix: "{{ condor_ip_range }}"
workers_group_name: "workers"
